//////////////////////////////////////////////////////////////////////////////////
// Config Automatically Generated by ALiVE ORBAT Creator
// Generated with Arma 3 version 206.148470 on Stable branch
// Generated with ALiVE version 1.15.0.2112041
//////////////////////////////////////////////////////////////////////////////////

class CfgFactionClasses {
    class I_RUArmy {
        displayName = "Republic of West Alaska";
        side = 2;
        flag = "\a3\Data_F_Enoch\Flags\flag_RUS_co.paa";
        icon = "\a3\Data_F_Enoch\Flags\flag_RUS_co.paa";
        priority = 0;
    };
};