class CfgPatches {
    class I_RUArmy {
        units[] = {
            "I_RUArmy_Commanding_Officer_01"
        };
        weapons[] = {};
        requiredVersion = 1.62;
        requiredAddons[] = {
            "UK3CB_Factions_CW_SOV_O_EARLY",
            "A3_Characters_F",
            "universal_uniforms",
            "cfp_uniforms",
            "ART_Character",
            "JMSLLTE_empire_mod",
            "uns_uniforms_VC_Khaki_Black",
            "uns_uniforms_VC_Main_Force_BLU",
            "uns_uniforms_VC_Main_Force_GRN",
            "w39_infantry_c",
            "CSA38II_characters_c",
            "CSA38II_characters2_c",
            "uns_men_NVA_65",
            "uns_men_NVA_68",
            "uns_men_NVA_crew",
            "uns_men_NVA_daccong",
            "uns_men_NVA_recon_65",
            "uns_men_VC_local",
            "uns_men_VC_mainforce",
            "uns_men_VC_mainforce_67",
            "uns_men_VC_mainforce_68",
            "uns_men_VC_recon",
            "uns_men_VC_regional",
            "A3_Sounds_F",
            "RUG_DSAI",
            "A3_Sounds_F_Exp",
            "jsrs_soundmod_complete_edition",
            "CBRN_gear",
            "fow_mortars_c",
            "ace_gforces",
            "ace_movement",
            "ace_medical_feedback",
            "CUP_Creatures_Military_BAF",
            "CUP_Creatures_Military_Germany",
            "CUP_Creatures_Military_NAPA",
            "CUP_Creatures_Military_PMC",
            "CUP_Creatures_Military_Russia",
            "CUP_Creatures_Military_Taki",
            "CUP_Creatures_Military_TakiInsurgents",
            "CUP_Creatures_Military_USMC",
            "cwr3_soldiers_fia",
            "cwr3_soldiers_ru",
            "cwr3_soldiers_us",
            "CUP_Creatures_Military_ACR",
            "CUP_Creatures_Military_CDF",
            "CUP_Creatures_Military_Chedaki",
            "CUP_Creatures_Military_Delta",
            "CUP_Creatures_Military_RACS",
            "CUP_Creatures_Military_SLA",
            "CUP_Creatures_Military_USArmy",
            "cwr3_hot_couple",
            "CUP_Creatures_Military_HIL",
            "A3_Data_F",
            "Sangin_Distirict_Helmand_Province",
            "PRA3_Kz",
            "A3_Data_F_Curator",
            "A3_Air_F_Heli",
            "A3_Map_IslaDuala3",
            "Mojave_NV",
            "jns_green_sea",
            "fow_map_Henderson",
            "fow_map_tarawa_c",
            "ace_thermals",
            "zen_attributes",
            "W39_czolgi",
            "psz_common",
            "tfar_core",
            "ace_refuel",
            "WW2_Assets_c_Vehicles_Extended_HUD_c",
            "AlkFrameWork_Default_UI",
            "CUP_Core",
            "cba_xeh"
        };
        author = "yaydrian yay";
        authors[] = {"yaydrian yay"};
    };
};