//////////////////////////////////////////////////////////////////////////////////
// Config Automatically Generated by ALiVE ORBAT Creator
// Generated with Arma 3 version 206.148470 on Stable branch
// Generated with ALiVE version 1.15.0.2112041
//////////////////////////////////////////////////////////////////////////////////


class CBA_Extended_EventHandlers_base;

class CfgVehicles {

    class I_RUSSTATEArmy_Natsgvardiya_Squad_Leader_01;
    class I_RUSSTATEArmy_Natsgvardiya_Squad_Leader_01_OCimport_01 : I_RUSSTATEArmy_Natsgvardiya_Squad_Leader_01 { scope = 0; class EventHandlers; };
    class I_RUSSTATEArmy_Natsgvardiya_Squad_Leader_01_OCimport_02 : I_RUSSTATEArmy_Natsgvardiya_Squad_Leader_01_OCimport_01 { class EventHandlers; };


    class I_RUArmy_Light_Mercenary_01 : I_RUSSTATEArmy_Natsgvardiya_Squad_Leader_01_OCimport_02 {
        author = "yaydrian yay";
        scope = 2;
        scopeCurator = 2;
        displayName = "Light Mercenary";
        side = 2;
        faction = "I_RUArmy";

        identityTypes[] = {"Head_Euro","LanguageRUS_F","LIB_Glasses"};

        uniformClass = "CUP_U_B_BDUv2_roll2_CEU";

        linkedItems[] = {"CUP_V_RUS_Smersh_New_Full","SP_Beret2_Green","ItemMap","ItemRadio","ItemCompass","ItemWatch"};
        respawnlinkedItems[] = {"CUP_V_RUS_Smersh_New_Full","SP_Beret2_Green","ItemMap","ItemRadio","ItemCompass","ItemWatch"};

        weapons[] = {"CUP_arifle_M16A1","CUP_hgun_Mac10","Binocular"};
        respawnWeapons[] = {"CUP_arifle_M16A1","CUP_hgun_Mac10","Binocular"};

        magazines[] = {"CUP_20Rnd_556x45_Stanag","CUP_30Rnd_45ACP_MAC10_M","CUP_20Rnd_556x45_Stanag","CUP_30Rnd_45ACP_MAC10_M"};
        respawnMagazines[] = {"CUP_20Rnd_556x45_Stanag","CUP_30Rnd_45ACP_MAC10_M","CUP_20Rnd_556x45_Stanag","CUP_30Rnd_45ACP_MAC10_M"};

        backpack = "B_LIB_SOV_RA_Rucksack_Green";

        ALiVE_orbatCreator_loadout[] = {{"CUP_arifle_M16A1","","","",{"CUP_20Rnd_556x45_Stanag",20},{},""},{},{"CUP_hgun_Mac10","","","",{"CUP_30Rnd_45ACP_MAC10_M",30},{},""},{"CUP_U_B_BDUv2_roll2_CEU",{{"PiR_bint",1},{"LIB_F1",2,1}}},{"CUP_V_RUS_Smersh_New_Full",{{"LIB_RDG",1,1},{"CUP_20Rnd_556x45_Stanag",10,20},{"CUP_30Rnd_45ACP_MAC10_M",6,30}}},{"B_LIB_SOV_RA_Rucksack_Green",{{"ACE_fieldDressing",5},{"ACE_Canteen",1},{"ACE_MRE_SteakVegetables",1}}},"SP_Beret2_Green","",{"Binocular","","","",{},{},""},{"ItemMap","","ItemRadio","ItemCompass","ItemWatch",""}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;[_this, 'insignia_test2'] call BIS_fnc_setUnitInsignia;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;
        ALiVE_orbatCreator_insignia = "insignia_test2";

    };

    class I_RUArmy_Mercenary_01 : I_RUArmy_Light_Mercenary_01 {
        author = "yaydrian yay";
        scope = 2;
        scopeCurator = 2;
        displayName = "Mercenary";
        side = 2;
        faction = "I_RUArmy";

        identityTypes[] = {"Head_Euro","LanguageRUS_F","LIB_Glasses"};

        uniformClass = "CUP_U_B_BDUv2_roll2_CEU";

        linkedItems[] = {"CFP_Smersh_Creme","SP_Beret2_Green","ItemMap","ItemRadio","ItemCompass","ItemWatch"};
        respawnlinkedItems[] = {"CFP_Smersh_Creme","SP_Beret2_Green","ItemMap","ItemRadio","ItemCompass","ItemWatch"};

        weapons[] = {"CUP_arifle_M16A1","CUP_hgun_Mac10","Binocular"};
        respawnWeapons[] = {"CUP_arifle_M16A1","CUP_hgun_Mac10","Binocular"};

        magazines[] = {"CUP_20Rnd_556x45_Stanag","CUP_30Rnd_45ACP_MAC10_M","CUP_20Rnd_556x45_Stanag","CUP_30Rnd_45ACP_MAC10_M"};
        respawnMagazines[] = {"CUP_20Rnd_556x45_Stanag","CUP_30Rnd_45ACP_MAC10_M","CUP_20Rnd_556x45_Stanag","CUP_30Rnd_45ACP_MAC10_M"};

        backpack = "CUP_O_RUS_Patrol_bag_Green_Shovel";

        ALiVE_orbatCreator_loadout[] = {{"CUP_arifle_M16A1","","","",{"CUP_20Rnd_556x45_Stanag",20},{},""},{},{"CUP_hgun_Mac10","","","",{"CUP_30Rnd_45ACP_MAC10_M",30},{},""},{"CUP_U_B_BDUv2_roll2_CEU",{{"LIB_F1",2,1},{"CUP_20Rnd_556x45_Stanag",1,20}}},{"CFP_Smersh_Creme",{{"LIB_RDG",1,1},{"CUP_30Rnd_45ACP_MAC10_M",5,30},{"CUP_20Rnd_556x45_Stanag",10,20}}},{"CUP_O_RUS_Patrol_bag_Green_Shovel",{{"CUP_HandGrenade_M67",1,1}}},"SP_Beret2_Green","",{"Binocular","","","",{},{},""},{"ItemMap","","ItemRadio","ItemCompass","ItemWatch",""}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;[_this, 'insignia_test2'] call BIS_fnc_setUnitInsignia;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;
        ALiVE_orbatCreator_insignia = "insignia_test2";

    };

    class I_RUArmy_Heavy_Mercenary_01 : I_RUArmy_Mercenary_01 {
        author = "yaydrian yay";
        scope = 2;
        scopeCurator = 2;
        displayName = "Heavy Mercenary";
        side = 2;
        faction = "I_RUArmy";

        identityTypes[] = {"Head_Euro","LanguageRUS_F","LIB_Glasses"};

        uniformClass = "CUP_U_B_BDUv2_roll2_CEU";

        linkedItems[] = {"CFP_Smersh_Creme","CUP_H_USArmy_Helmet_M1_plain_M81","ItemMap","ItemRadio","ItemCompass","ItemWatch"};
        respawnlinkedItems[] = {"CFP_Smersh_Creme","CUP_H_USArmy_Helmet_M1_plain_M81","ItemMap","ItemRadio","ItemCompass","ItemWatch"};

        weapons[] = {"CUP_lmg_M60","CUP_hgun_Mac10","Binocular"};
        respawnWeapons[] = {"CUP_lmg_M60","CUP_hgun_Mac10","Binocular"};

        magazines[] = {"CUP_100Rnd_TE4_LRT4_White_Tracer_762x51_Belt_M","CUP_30Rnd_45ACP_MAC10_M","CUP_100Rnd_TE4_LRT4_White_Tracer_762x51_Belt_M","CUP_30Rnd_45ACP_MAC10_M"};
        respawnMagazines[] = {"CUP_100Rnd_TE4_LRT4_White_Tracer_762x51_Belt_M","CUP_30Rnd_45ACP_MAC10_M","CUP_100Rnd_TE4_LRT4_White_Tracer_762x51_Belt_M","CUP_30Rnd_45ACP_MAC10_M"};

        backpack = "CUP_O_RUS_Patrol_bag_Green_Shovel";

        ALiVE_orbatCreator_loadout[] = {{"CUP_lmg_M60","","","",{"CUP_100Rnd_TE4_LRT4_White_Tracer_762x51_Belt_M",100},{},""},{},{"CUP_hgun_Mac10","","","",{"CUP_30Rnd_45ACP_MAC10_M",30},{},""},{"CUP_U_B_BDUv2_roll2_CEU",{{"LIB_F1",2,1}}},{"CFP_Smersh_Creme",{{"PiR_bint",1},{"LIB_RDG",1,1},{"CUP_30Rnd_45ACP_MAC10_M",5,30},{"CUP_100Rnd_TE4_LRT4_White_Tracer_762x51_Belt_M",1,100}}},{"CUP_O_RUS_Patrol_bag_Green_Shovel",{{"CUP_HandGrenade_M67",1,1},{"CUP_100Rnd_TE4_LRT4_White_Tracer_762x51_Belt_M",6,100}}},"CUP_H_USArmy_Helmet_M1_plain_M81","",{"Binocular","","","",{},{},""},{"ItemMap","","ItemRadio","ItemCompass","ItemWatch",""}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;[_this, 'insignia_test2'] call BIS_fnc_setUnitInsignia;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;
        ALiVE_orbatCreator_insignia = "insignia_test2";

    };

    class I_RUArmy_Mercenary_Boss_01 : I_RUArmy_Light_Mercenary_01 {
        author = "yaydrian yay";
        scope = 2;
        scopeCurator = 2;
        displayName = "Mercenary Boss";
        side = 2;
        faction = "I_RUArmy";

        identityTypes[] = {"Head_Euro","LanguageRUS_F","LIB_Glasses"};

        uniformClass = "CUP_U_B_BDUv2_roll2_CEU";

        linkedItems[] = {"V_LIB_SOV_RA_SniperVest","CUP_H_ChDKZ_Cap","ItemMap","ItemRadio","ItemCompass","ItemWatch"};
        respawnlinkedItems[] = {"V_LIB_SOV_RA_SniperVest","CUP_H_ChDKZ_Cap","ItemMap","ItemRadio","ItemCompass","ItemWatch"};

        weapons[] = {"CUP_arifle_M16A1","CUP_hgun_Colt1911","Binocular"};
        respawnWeapons[] = {"CUP_arifle_M16A1","CUP_hgun_Colt1911","Binocular"};

        magazines[] = {"CUP_20Rnd_556x45_Stanag","CUP_7Rnd_45ACP_1911","CUP_20Rnd_556x45_Stanag","CUP_7Rnd_45ACP_1911"};
        respawnMagazines[] = {"CUP_20Rnd_556x45_Stanag","CUP_7Rnd_45ACP_1911","CUP_20Rnd_556x45_Stanag","CUP_7Rnd_45ACP_1911"};

        backpack = "B_LIB_SOV_RA_Rucksack_Green";

        ALiVE_orbatCreator_loadout[] = {{"CUP_arifle_M16A1","","","",{"CUP_20Rnd_556x45_Stanag",20},{},""},{},{"CUP_hgun_Colt1911","","","",{"CUP_7Rnd_45ACP_1911",7},{},""},{"CUP_U_B_BDUv2_roll2_CEU",{{"PiR_bint",1},{"LIB_F1",2,1}}},{"V_LIB_SOV_RA_SniperVest",{{"PiR_bint",1},{"LIB_RDG",1,1},{"CUP_20Rnd_556x45_Stanag",5,20}}},{"B_LIB_SOV_RA_Rucksack_Green",{{"ACE_fieldDressing",5},{"ACE_Canteen",1},{"ACE_MRE_SteakVegetables",1},{"CUP_7Rnd_45ACP_1911",8,7}}},"CUP_H_ChDKZ_Cap","",{"Binocular","","","",{},{},""},{"ItemMap","","ItemRadio","ItemCompass","ItemWatch",""}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;[_this, 'insignia_test2'] call BIS_fnc_setUnitInsignia;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;
        ALiVE_orbatCreator_insignia = "insignia_test2";

    };

    class I_RUArmy_Mercenary_Marksman_01 : I_RUArmy_Light_Mercenary_01 {
        author = "yaydrian yay";
        scope = 2;
        scopeCurator = 2;
        displayName = "Mercenary Marksman";
        side = 2;
        faction = "I_RUArmy";

        identityTypes[] = {"Head_Euro","LanguageRUS_F","LIB_Glasses"};

        uniformClass = "CUP_U_B_BDUv2_roll2_CEU";

        linkedItems[] = {"CFP_Smersh_Creme","SP_Beret2_Green","ItemMap","ItemRadio","ItemCompass","ItemWatch"};
        respawnlinkedItems[] = {"CFP_Smersh_Creme","SP_Beret2_Green","ItemMap","ItemRadio","ItemCompass","ItemWatch"};

        weapons[] = {"CUP_srifle_SVD","CUP_hgun_Colt1911","Binocular"};
        respawnWeapons[] = {"CUP_srifle_SVD","CUP_hgun_Colt1911","Binocular"};

        magazines[] = {"CUP_10Rnd_762x54_SVD_M","CUP_7Rnd_45ACP_1911","CUP_10Rnd_762x54_SVD_M","CUP_7Rnd_45ACP_1911"};
        respawnMagazines[] = {"CUP_10Rnd_762x54_SVD_M","CUP_7Rnd_45ACP_1911","CUP_10Rnd_762x54_SVD_M","CUP_7Rnd_45ACP_1911"};

        backpack = "B_LIB_SOV_RA_Rucksack_Green";

        ALiVE_orbatCreator_loadout[] = {{"CUP_srifle_SVD","","","CUP_optic_PSO_1",{"CUP_10Rnd_762x54_SVD_M",10},{},""},{},{"CUP_hgun_Colt1911","","","",{"CUP_7Rnd_45ACP_1911",7},{},""},{"CUP_U_B_BDUv2_roll2_CEU",{{"PiR_bint",1},{"LIB_F1",2,1}}},{"CFP_Smersh_Creme",{{"PiR_bint",1},{"LIB_RDG",1,1},{"CUP_7Rnd_45ACP_1911",4,7},{"CUP_10Rnd_762x54_SVD_M",12,10}}},{"B_LIB_SOV_RA_Rucksack_Green",{{"ACE_fieldDressing",5},{"ACE_Canteen",1},{"ACE_MRE_SteakVegetables",1},{"CUP_7Rnd_45ACP_1911",2,7}}},"SP_Beret2_Green","OPTRE_Glasses_Cigarette",{"Binocular","","","",{},{},""},{"ItemMap","","ItemRadio","ItemCompass","ItemWatch",""}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;[_this, 'insignia_test2'] call BIS_fnc_setUnitInsignia;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;
        ALiVE_orbatCreator_insignia = "insignia_test2";

    };

    class I_RUArmy_Russian_Native_Conscript_01 : I_RUArmy_Light_Mercenary_01 {
        author = "yaydrian yay";
        scope = 2;
        scopeCurator = 2;
        displayName = "Russian Native Conscript";
        side = 2;
        faction = "I_RUArmy";

        identityTypes[] = {"Head_Asian","LanguageRUS_F","LIB_Glasses"};

        uniformClass = "CUP_U_B_BDUv2_roll2_CEU";

        linkedItems[] = {"CFP_Smersh_Creme","CUP_H_RUS_SSH68_olive","ItemMap","ItemRadio","ItemCompass","ItemWatch"};
        respawnlinkedItems[] = {"CFP_Smersh_Creme","CUP_H_RUS_SSH68_olive","ItemMap","ItemRadio","ItemCompass","ItemWatch"};

        weapons[] = {"CUP_arifle_AKM_Early","LIB_TT33","Binocular"};
        respawnWeapons[] = {"CUP_arifle_AKM_Early","LIB_TT33","Binocular"};

        magazines[] = {"CUP_30Rnd_762x39_AK47_bakelite_M","LIB_8Rnd_762x25","CUP_30Rnd_762x39_AK47_bakelite_M","LIB_8Rnd_762x25"};
        respawnMagazines[] = {"CUP_30Rnd_762x39_AK47_bakelite_M","LIB_8Rnd_762x25","CUP_30Rnd_762x39_AK47_bakelite_M","LIB_8Rnd_762x25"};

        backpack = "B_LIB_SOV_RA_Rucksack_Green";

        ALiVE_orbatCreator_loadout[] = {{"CUP_arifle_AKM_Early","","","",{"CUP_30Rnd_762x39_AK47_bakelite_M",30},{},""},{},{"LIB_TT33","","","",{"LIB_8Rnd_762x25",8},{},""},{"CUP_U_B_BDUv2_roll2_CEU",{{"PiR_bint",1},{"LIB_F1",2,1},{"LIB_8Rnd_762x25",1,8}}},{"CFP_Smersh_Creme",{{"PiR_bint",1},{"LIB_RDG",1,1},{"CUP_30Rnd_762x39_AK47_bakelite_M",10,30},{"LIB_8Rnd_762x25",5,8}}},{"B_LIB_SOV_RA_Rucksack_Green",{{"ACE_fieldDressing",5},{"ACE_Canteen",1},{"ACE_MRE_SteakVegetables",1},{"CUP_HandGrenade_RGD5",1,1}}},"CUP_H_RUS_SSH68_olive","",{"Binocular","","","",{},{},""},{"ItemMap","","ItemRadio","ItemCompass","ItemWatch",""}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;[_this, 'insignia_test2'] call BIS_fnc_setUnitInsignia;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;
        ALiVE_orbatCreator_insignia = "insignia_test2";

    };

};