//////////////////////////////////////////////////////////////////////////////////
// Config Automatically Generated by ALiVE ORBAT Creator
// Generated with Arma 3 version 206.148470 on Stable branch
// Generated with ALiVE version 1.15.0.2112041
//////////////////////////////////////////////////////////////////////////////////

class CfgFactionClasses {
    class B_BGArmy {
        displayName = "Ordenstaat Burgund";
        side = 1;
        flag = "";
        icon = "";
        priority = 0;
    };
};