//////////////////////////////////////////////////////////////////////////////////
// Config Automatically Generated by ALiVE ORBAT Creator
// Generated with Arma 3 version 206.148470 on Stable branch
// Generated with ALiVE version 1.15.0.2112041
//////////////////////////////////////////////////////////////////////////////////


class CBA_Extended_EventHandlers_base;

class CfgVehicles {

    class LIB_GER_unterofficer_HeerUfwStg44;
    class LIB_GER_unterofficer_HeerUfwStg44_OCimport_01 : LIB_GER_unterofficer_HeerUfwStg44 { scope = 0; class EventHandlers; };
    class LIB_GER_unterofficer_HeerUfwStg44_OCimport_02 : LIB_GER_unterofficer_HeerUfwStg44_OCimport_01 { class EventHandlers; };


    class B_BGArmy_Schutzstaffel_Infantryman_01 : LIB_GER_unterofficer_HeerUfwStg44_OCimport_02 {
        author = "yaydrian yay";
        scope = 2;
        scopeCurator = 2;
        displayName = "Infantryman";
        side = 1;
        faction = "B_BGArmy";

        identityTypes[] = {"Head_Euro","Language_LIB_GER","GER_Head"};

        uniformClass = "CUP_U_B_BDUv2_DPM_OD";

        linkedItems[] = {"CUP_V_B_PASGT_OD","H_LIB_GER_Helmet_SSbT1","ItemMap","ItemCompass","ItemWatch"};
        respawnlinkedItems[] = {"CUP_V_B_PASGT_OD","H_LIB_GER_Helmet_SSbT1","ItemMap","ItemCompass","ItemWatch"};

        weapons[] = {"CUP_arifle_Steyr_Stg58","LIB_WaltherPPK","LIB_Binocular_GER"};
        respawnWeapons[] = {"CUP_arifle_Steyr_Stg58","LIB_WaltherPPK","LIB_Binocular_GER"};

        magazines[] = {"CUP_20Rnd_762x51_FNFAL_M","fow_8Rnd_9x19","CUP_20Rnd_762x51_FNFAL_M","fow_8Rnd_9x19"};
        respawnMagazines[] = {"CUP_20Rnd_762x51_FNFAL_M","fow_8Rnd_9x19","CUP_20Rnd_762x51_FNFAL_M","fow_8Rnd_9x19"};

        backpack = "CUP_O_RUS_Patrol_bag_Green";

        ALiVE_orbatCreator_loadout[] = {{"CUP_arifle_Steyr_Stg58","","","",{"CUP_20Rnd_762x51_FNFAL_M",20},{},"CUP_bipod_FNFAL"},{},{"LIB_WaltherPPK","","","",{"fow_8Rnd_9x19",8},{},""},{"CUP_U_B_BDUv2_DPM_OD",{{"PiR_bint",2},{"fow_8Rnd_9x19",5,8}}},{"CUP_V_B_PASGT_OD",{{"CUP_20Rnd_762x51_FNFAL_M",7,20},{"fow_8Rnd_9x19",3,8}}},{"CUP_O_RUS_Patrol_bag_Green",{{"CUP_20Rnd_762x51_FNFAL_M",5,20},{"LIB_NB39",2,1}}},"H_LIB_GER_Helmet_SSbT1","",{"LIB_Binocular_GER","","","",{},{},""},{"ItemMap","","","ItemCompass","ItemWatch",""}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;[_this, 'insignia_test3'] call BIS_fnc_setUnitInsignia;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;
        ALiVE_orbatCreator_insignia = "insignia_test3";

    };

    class B_BGArmy_Heavy_Infantryman_01 : B_BGArmy_Schutzstaffel_Infantryman_01 {
        author = "yaydrian yay";
        scope = 2;
        scopeCurator = 2;
        displayName = "Heavy Infantryman";
        side = 1;
        faction = "B_BGArmy";

        identityTypes[] = {"Head_Euro","Language_LIB_GER","GER_Head"};

        uniformClass = "CUP_U_B_BDUv2_DPM_OD";

        linkedItems[] = {"CUP_V_B_PASGT_OD","H_LIB_GER_Helmet_SSbT1","ItemMap","ItemCompass","ItemWatch"};
        respawnlinkedItems[] = {"CUP_V_B_PASGT_OD","H_LIB_GER_Helmet_SSbT1","ItemMap","ItemCompass","ItemWatch"};

        weapons[] = {"CUP_lmg_MG3_rail","LIB_WaltherPPK","LIB_Binocular_GER"};
        respawnWeapons[] = {"CUP_lmg_MG3_rail","LIB_WaltherPPK","LIB_Binocular_GER"};

        magazines[] = {"CUP_120Rnd_TE4_LRT4_White_Tracer_762x51_Belt_M","fow_8Rnd_9x19","CUP_120Rnd_TE4_LRT4_White_Tracer_762x51_Belt_M","fow_8Rnd_9x19"};
        respawnMagazines[] = {"CUP_120Rnd_TE4_LRT4_White_Tracer_762x51_Belt_M","fow_8Rnd_9x19","CUP_120Rnd_TE4_LRT4_White_Tracer_762x51_Belt_M","fow_8Rnd_9x19"};

        backpack = "CUP_O_RUS_Patrol_bag_Green";

        ALiVE_orbatCreator_loadout[] = {{"CUP_lmg_MG3_rail","","","",{"CUP_120Rnd_TE4_LRT4_White_Tracer_762x51_Belt_M",120},{},""},{},{"LIB_WaltherPPK","","","",{"fow_8Rnd_9x19",8},{},""},{"CUP_U_B_BDUv2_DPM_OD",{{"PiR_bint",2},{"fow_8Rnd_9x19",5,8}}},{"CUP_V_B_PASGT_OD",{{"fow_8Rnd_9x19",3,8},{"CUP_120Rnd_TE4_LRT4_White_Tracer_762x51_Belt_M",1,120}}},{"CUP_O_RUS_Patrol_bag_Green",{{"PiR_bint",1},{"LIB_NB39",2,1},{"CUP_120Rnd_TE4_LRT4_White_Tracer_762x51_Belt_M",5,120}}},"H_LIB_GER_Helmet_SSbT1","",{"LIB_Binocular_GER","","","",{},{},""},{"ItemMap","","","ItemCompass","ItemWatch",""}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class B_BGArmy_Light_Infantryman_01 : B_BGArmy_Schutzstaffel_Infantryman_01 {
        author = "yaydrian yay";
        scope = 2;
        scopeCurator = 2;
        displayName = "Light Infantryman";
        side = 1;
        faction = "B_BGArmy";

        identityTypes[] = {"Head_Euro","Language_LIB_GER","GER_Head"};

        uniformClass = "CUP_U_B_BDUv2_DPM_OD";

        linkedItems[] = {"CUP_V_RUS_Smersh_New_Buttpack","H_LIB_GER_CapOfficer_SS","ItemMap","ItemCompass","ItemWatch"};
        respawnlinkedItems[] = {"CUP_V_RUS_Smersh_New_Buttpack","H_LIB_GER_CapOfficer_SS","ItemMap","ItemCompass","ItemWatch"};

        weapons[] = {"CUP_arifle_Steyr_Stg58","LIB_WaltherPPK","LIB_Binocular_GER"};
        respawnWeapons[] = {"CUP_arifle_Steyr_Stg58","LIB_WaltherPPK","LIB_Binocular_GER"};

        magazines[] = {"CUP_20Rnd_762x51_FNFAL_M","fow_8Rnd_9x19","CUP_20Rnd_762x51_FNFAL_M","fow_8Rnd_9x19"};
        respawnMagazines[] = {"CUP_20Rnd_762x51_FNFAL_M","fow_8Rnd_9x19","CUP_20Rnd_762x51_FNFAL_M","fow_8Rnd_9x19"};

        backpack = "CUP_O_RUS_Patrol_bag_Green";

        ALiVE_orbatCreator_loadout[] = {{"CUP_arifle_Steyr_Stg58","","","",{"CUP_20Rnd_762x51_FNFAL_M",20},{},"CUP_bipod_FNFAL"},{},{"LIB_WaltherPPK","","","",{"fow_8Rnd_9x19",8},{},""},{"CUP_U_B_BDUv2_DPM_OD",{{"PiR_bint",2},{"fow_8Rnd_9x19",5,8}}},{"CUP_V_RUS_Smersh_New_Buttpack",{{"CUP_20Rnd_762x51_FNFAL_M",7,20},{"fow_8Rnd_9x19",3,8}}},{"CUP_O_RUS_Patrol_bag_Green",{{"PiR_bint",1},{"CUP_20Rnd_762x51_FNFAL_M",5,20},{"LIB_NB39",2,1}}},"H_LIB_GER_CapOfficer_SS","",{"LIB_Binocular_GER","","","",{},{},""},{"ItemMap","","","ItemCompass","ItemWatch",""}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class B_BGArmy_Security_Police_Officer_01 : B_BGArmy_Schutzstaffel_Infantryman_01 {
        author = "yaydrian yay";
        scope = 2;
        scopeCurator = 2;
        displayName = "Security Police Officer";
        side = 1;
        faction = "B_BGArmy";

        identityTypes[] = {"Head_Euro","Language_LIB_GER","GER_Head"};

        uniformClass = "CUP_U_B_BDUv2_DPM";

        linkedItems[] = {"CUP_V_B_PASGT_OD","H_LIB_GER_OfficerCap_SS","ItemMap","ItemCompass","ItemWatch"};
        respawnlinkedItems[] = {"CUP_V_B_PASGT_OD","H_LIB_GER_OfficerCap_SS","ItemMap","ItemCompass","ItemWatch"};

        weapons[] = {"CUP_arifle_Steyr_Stg58","LIB_WaltherPPK","LIB_Binocular_GER"};
        respawnWeapons[] = {"CUP_arifle_Steyr_Stg58","LIB_WaltherPPK","LIB_Binocular_GER"};

        magazines[] = {"CUP_20Rnd_762x51_FNFAL_M","fow_8Rnd_9x19","CUP_20Rnd_762x51_FNFAL_M","fow_8Rnd_9x19"};
        respawnMagazines[] = {"CUP_20Rnd_762x51_FNFAL_M","fow_8Rnd_9x19","CUP_20Rnd_762x51_FNFAL_M","fow_8Rnd_9x19"};

        ALiVE_orbatCreator_loadout[] = {{"CUP_arifle_Steyr_Stg58","","","",{"CUP_20Rnd_762x51_FNFAL_M",20},{},"CUP_bipod_FNFAL"},{},{"LIB_WaltherPPK","","","",{"fow_8Rnd_9x19",8},{},""},{"CUP_U_B_BDUv2_DPM",{{"PiR_bint",2},{"fow_8Rnd_9x19",5,8}}},{"CUP_V_B_PASGT_OD",{{"CUP_20Rnd_762x51_FNFAL_M",5,20},{"fow_8Rnd_9x19",8,8}}},{},"H_LIB_GER_OfficerCap_SS","",{"LIB_Binocular_GER","","","",{},{},""},{"ItemMap","","","ItemCompass","ItemWatch",""}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;[_this, 'insignia_test3'] call BIS_fnc_setUnitInsignia;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;
        ALiVE_orbatCreator_insignia = "insignia_test3";

    };

    class B_BGArmy_Field_Officer_01 : B_BGArmy_Schutzstaffel_Infantryman_01 {
        author = "yaydrian yay";
        scope = 2;
        scopeCurator = 2;
        displayName = "Field Officer";
        side = 1;
        faction = "B_BGArmy";

        identityTypes[] = {"Head_Euro","Language_LIB_GER","GER_Head"};

        uniformClass = "CUP_U_B_BDUv2_DPM_OD";

        linkedItems[] = {"CUP_V_B_PASGT_OD","H_LIB_GER_OfficerCap_SS_Uffz","ItemMap","ItemCompass","ItemWatch"};
        respawnlinkedItems[] = {"CUP_V_B_PASGT_OD","H_LIB_GER_OfficerCap_SS_Uffz","ItemMap","ItemCompass","ItemWatch"};

        weapons[] = {"CUP_arifle_Steyr_Stg58","LIB_WaltherPPK","LIB_Binocular_GER"};
        respawnWeapons[] = {"CUP_arifle_Steyr_Stg58","LIB_WaltherPPK","LIB_Binocular_GER"};

        magazines[] = {"CUP_20Rnd_762x51_FNFAL_M","fow_8Rnd_9x19","CUP_20Rnd_762x51_FNFAL_M","fow_8Rnd_9x19"};
        respawnMagazines[] = {"CUP_20Rnd_762x51_FNFAL_M","fow_8Rnd_9x19","CUP_20Rnd_762x51_FNFAL_M","fow_8Rnd_9x19"};

        backpack = "CUP_O_RUS_Patrol_bag_Green";

        ALiVE_orbatCreator_loadout[] = {{"CUP_arifle_Steyr_Stg58","","","",{"CUP_20Rnd_762x51_FNFAL_M",20},{},"CUP_bipod_FNFAL"},{},{"LIB_WaltherPPK","","","",{"fow_8Rnd_9x19",8},{},""},{"CUP_U_B_BDUv2_DPM_OD",{{"PiR_bint",2},{"EF_SC_MG2_NV",1},{"fow_8Rnd_9x19",5,8}}},{"CUP_V_B_PASGT_OD",{{"CUP_20Rnd_762x51_FNFAL_M",7,20},{"fow_8Rnd_9x19",3,8}}},{"CUP_O_RUS_Patrol_bag_Green",{{"PiR_bint",1},{"CUP_20Rnd_762x51_FNFAL_M",5,20},{"LIB_NB39",2,1}}},"H_LIB_GER_OfficerCap_SS_Uffz","",{"LIB_Binocular_GER","","","",{},{},""},{"ItemMap","","","ItemCompass","ItemWatch",""}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;[_this, 'insignia_test3'] call BIS_fnc_setUnitInsignia;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;
        ALiVE_orbatCreator_insignia = "insignia_test3";

    };

    class B_BGArmy_Special_Infantry_Unit_01 : B_BGArmy_Schutzstaffel_Infantryman_01 {
        author = "yaydrian yay";
        scope = 2;
        scopeCurator = 2;
        displayName = "Special Infantry Unit";
        side = 1;
        faction = "B_BGArmy";

        identityTypes[] = {"Head_Euro","Language_LIB_GER","GER_Head"};

        uniformClass = "CUP_U_B_BDUv2_DPM";

        linkedItems[] = {"CUP_V_B_PASGT_OD","H_LIB_GER_HelmetCamo_H02","ItemMap","ItemCompass","ItemWatch","N_LIB_GER_HelmetUtility_GrassOak"};
        respawnlinkedItems[] = {"CUP_V_B_PASGT_OD","H_LIB_GER_HelmetCamo_H02","ItemMap","ItemCompass","ItemWatch","N_LIB_GER_HelmetUtility_GrassOak"};

        weapons[] = {"CUP_arifle_Steyr_Stg58","LIB_WaltherPPK","LIB_Binocular_GER"};
        respawnWeapons[] = {"CUP_arifle_Steyr_Stg58","LIB_WaltherPPK","LIB_Binocular_GER"};

        magazines[] = {"CUP_20Rnd_762x51_FNFAL_M","fow_8Rnd_9x19","CUP_20Rnd_762x51_FNFAL_M","fow_8Rnd_9x19"};
        respawnMagazines[] = {"CUP_20Rnd_762x51_FNFAL_M","fow_8Rnd_9x19","CUP_20Rnd_762x51_FNFAL_M","fow_8Rnd_9x19"};

        backpack = "CUP_O_RUS_Patrol_bag_Green";

        ALiVE_orbatCreator_loadout[] = {{"CUP_arifle_Steyr_Stg58","","","",{"CUP_20Rnd_762x51_FNFAL_M",20},{},"CUP_bipod_FNFAL"},{},{"LIB_WaltherPPK","","","",{"fow_8Rnd_9x19",8},{},""},{"CUP_U_B_BDUv2_DPM",{{"PiR_bint",2},{"ff_sscover_p_2",1},{"fow_8Rnd_9x19",5,8}}},{"CUP_V_B_PASGT_OD",{{"CUP_20Rnd_762x51_FNFAL_M",7,20},{"fow_8Rnd_9x19",3,8}}},{"CUP_O_RUS_Patrol_bag_Green",{{"PiR_bint",2},{"CUP_20Rnd_762x51_FNFAL_M",5,20},{"LIB_Shg24x7",1,1}}},"H_LIB_GER_HelmetCamo_H02","SE_GP7_Gas_Mask",{"LIB_Binocular_GER","","","",{},{},""},{"ItemMap","","","ItemCompass","ItemWatch","N_LIB_GER_HelmetUtility_GrassOak"}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

};