//////////////////////////////////////////////////////////////////////////////////
// Config Automatically Generated by ALiVE ORBAT Creator
// Generated with Arma 3 version 206.148470 on Stable branch
// Generated with ALiVE version 1.15.0.2112041
//////////////////////////////////////////////////////////////////////////////////

class CfgFactionClasses {
    class I_DBArmy {
        displayName = "Dirlewanger Brigade";
        side = 2;
        flag = "";
        icon = "";
        priority = 0;
    };
};