//////////////////////////////////////////////////////////////////////////////////
// Config Automatically Generated by ALiVE ORBAT Creator
// Generated with Arma 3 version 206.148470 on Stable branch
// Generated with ALiVE version 1.15.0.2112041
//////////////////////////////////////////////////////////////////////////////////


class CBA_Extended_EventHandlers_base;

class CfgVehicles {

    class LIB_GER_unterofficer_HeerUfw2Stg44;
    class LIB_GER_unterofficer_HeerUfw2Stg44_OCimport_01 : LIB_GER_unterofficer_HeerUfw2Stg44 { scope = 0; class EventHandlers; };
    class LIB_GER_unterofficer_HeerUfw2Stg44_OCimport_02 : LIB_GER_unterofficer_HeerUfw2Stg44_OCimport_01 { class EventHandlers; };


    class I_DBArmy__01 : LIB_GER_unterofficer_HeerUfw2Stg44_OCimport_02 {
        author = "yaydrian yay";
        scope = 2;
        scopeCurator = 2;
        displayName = "Brigade Pillager";
        side = 2;
        faction = "I_DBArmy";

        identityTypes[] = {"Language_LIB_GER","GER_Head"};

        uniformClass = "CUP_U_B_BDUv2_OD";

        linkedItems[] = {"V_LIB_GER_VestKar98","H_LIB_GER_Ushanka","ItemMap","ItemCompass","ItemWatch"};
        respawnlinkedItems[] = {"V_LIB_GER_VestKar98","H_LIB_GER_Ushanka","ItemMap","ItemCompass","ItemWatch"};

        weapons[] = {"CUP_arifle_Steyr_Stg58","LIB_WaltherPPK","LIB_Binocular_GER"};
        respawnWeapons[] = {"CUP_arifle_Steyr_Stg58","LIB_WaltherPPK","LIB_Binocular_GER"};

        magazines[] = {"CUP_20Rnd_762x51_FNFAL_M","fow_8Rnd_9x19","CUP_20Rnd_762x51_FNFAL_M","fow_8Rnd_9x19"};
        respawnMagazines[] = {"CUP_20Rnd_762x51_FNFAL_M","fow_8Rnd_9x19","CUP_20Rnd_762x51_FNFAL_M","fow_8Rnd_9x19"};

        backpack = "B_LIB_GER_Backpack";

        ALiVE_orbatCreator_loadout[] = {{"CUP_arifle_Steyr_Stg58","","","",{"CUP_20Rnd_762x51_FNFAL_M",20},{},"CUP_bipod_FNFAL"},{},{"LIB_WaltherPPK","","","",{"fow_8Rnd_9x19",8},{},""},{"CUP_U_B_BDUv2_OD",{{"LIB_ACC_K98_Bayo",1},{"PiR_bint",1},{"LIB_M39",1,1},{"CUP_20Rnd_762x51_FNFAL_M",1,20},{"fow_8Rnd_9x19",1,8}}},{"V_LIB_GER_VestKar98",{{"PiR_bint",1},{"fow_8Rnd_9x19",5,8},{"LIB_NB39",1,1}}},{"B_LIB_GER_Backpack",{{"CUP_20Rnd_762x51_FNFAL_M",9,20}}},"H_LIB_GER_Ushanka","",{"LIB_Binocular_GER","","","",{},{},""},{"ItemMap","","","ItemCompass","ItemWatch",""}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;[_this, 'insignia_test4'] call BIS_fnc_setUnitInsignia;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;
        ALiVE_orbatCreator_insignia = "insignia_test4";

    };

    class I_DBArmy_Brigade_Veteran_01 : I_DBArmy__01 {
        author = "yaydrian yay";
        scope = 2;
        scopeCurator = 2;
        displayName = "Brigade Veteran";
        side = 2;
        faction = "I_DBArmy";

        identityTypes[] = {"Language_LIB_GER","GER_Head"};

        uniformClass = "CUP_U_B_BDUv2_dirty_OD";

        linkedItems[] = {"V_LIB_GER_VestKar98","H_LIB_GER_Helmet","ItemMap","ItemCompass","ItemWatch"};
        respawnlinkedItems[] = {"V_LIB_GER_VestKar98","H_LIB_GER_Helmet","ItemMap","ItemCompass","ItemWatch"};

        weapons[] = {"CUP_arifle_Steyr_Stg58","LIB_WaltherPPK","LIB_Binocular_GER"};
        respawnWeapons[] = {"CUP_arifle_Steyr_Stg58","LIB_WaltherPPK","LIB_Binocular_GER"};

        magazines[] = {"CUP_20Rnd_762x51_FNFAL_M","fow_8Rnd_9x19","CUP_20Rnd_762x51_FNFAL_M","fow_8Rnd_9x19"};
        respawnMagazines[] = {"CUP_20Rnd_762x51_FNFAL_M","fow_8Rnd_9x19","CUP_20Rnd_762x51_FNFAL_M","fow_8Rnd_9x19"};

        backpack = "B_LIB_GER_Backpack";

        ALiVE_orbatCreator_loadout[] = {{"CUP_arifle_Steyr_Stg58","","","",{"CUP_20Rnd_762x51_FNFAL_M",20},{},"CUP_bipod_FNFAL"},{},{"LIB_WaltherPPK","","","",{"fow_8Rnd_9x19",8},{},""},{"CUP_U_B_BDUv2_dirty_OD",{{"LIB_ACC_K98_Bayo",1},{"PiR_bint",1},{"LIB_M39",1,1},{"CUP_20Rnd_762x51_FNFAL_M",1,20},{"fow_8Rnd_9x19",1,8}}},{"V_LIB_GER_VestKar98",{{"PiR_bint",1},{"fow_8Rnd_9x19",5,8},{"LIB_NB39",1,1}}},{"B_LIB_GER_Backpack",{{"CUP_20Rnd_762x51_FNFAL_M",9,20}}},"H_LIB_GER_Helmet","",{"LIB_Binocular_GER","","","",{},{},""},{"ItemMap","","","ItemCompass","ItemWatch",""}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;[_this, 'insignia_test4'] call BIS_fnc_setUnitInsignia;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;
        ALiVE_orbatCreator_insignia = "insignia_test4";

    };

    class I_DBArmy_Brigade_Penal_Unit_01 : I_DBArmy__01 {
        author = "yaydrian yay";
        scope = 2;
        scopeCurator = 2;
        displayName = "Brigade Penal Unit";
        side = 2;
        faction = "I_DBArmy";

        identityTypes[] = {"Language_LIB_GER","GER_Head"};

        uniformClass = "CUP_U_B_BDUv2_OD";

        linkedItems[] = {"V_LIB_SOV_IShBrVestPPShMag","UK3CB_TKA_I_H_SSh68_Oli","ItemMap","ItemCompass","ItemWatch"};
        respawnlinkedItems[] = {"V_LIB_SOV_IShBrVestPPShMag","UK3CB_TKA_I_H_SSh68_Oli","ItemMap","ItemCompass","ItemWatch"};

        weapons[] = {"CUP_arifle_AKM_Early","LIB_Binocular_GER"};
        respawnWeapons[] = {"CUP_arifle_AKM_Early","LIB_Binocular_GER"};

        magazines[] = {"CUP_30Rnd_762x39_AK47_bakelite_M","CUP_30Rnd_762x39_AK47_bakelite_M"};
        respawnMagazines[] = {"CUP_30Rnd_762x39_AK47_bakelite_M","CUP_30Rnd_762x39_AK47_bakelite_M"};

        backpack = "B_LIB_SOV_RA_Rucksack_Green";

        ALiVE_orbatCreator_loadout[] = {{"CUP_arifle_AKM_Early","","","",{"CUP_30Rnd_762x39_AK47_bakelite_M",30},{},""},{},{},{"CUP_U_B_BDUv2_OD",{{"LIB_ACC_K98_Bayo",1},{"PiR_bint",1},{"LIB_M39",1,1}}},{"V_LIB_SOV_IShBrVestPPShMag",{{"PiR_bint",2},{"LIB_NB39",1,1},{"CUP_30Rnd_762x39_AK47_bakelite_M",5,30}}},{"B_LIB_SOV_RA_Rucksack_Green",{{"CUP_30Rnd_762x39_AK47_bakelite_M",5,30},{"LIB_Rg42",1,1}}},"UK3CB_TKA_I_H_SSh68_Oli","",{"LIB_Binocular_GER","","","",{},{},""},{"ItemMap","","","ItemCompass","ItemWatch",""}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;[_this, 'insignia_test4'] call BIS_fnc_setUnitInsignia;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;
        ALiVE_orbatCreator_insignia = "insignia_test4";

    };

    class I_DBArmy_Brigade_Officer_01 : I_DBArmy_Brigade_Veteran_01 {
        author = "yaydrian yay";
        scope = 2;
        scopeCurator = 2;
        displayName = "Brigade Officer";
        side = 2;
        faction = "I_DBArmy";

        identityTypes[] = {"Language_LIB_GER","GER_Head"};

        uniformClass = "CUP_U_B_BDUv2_dirty_OD";

        linkedItems[] = {"V_LIB_GER_FieldOfficer","H_LIB_GER_Cap","ItemMap","ItemCompass","ItemWatch"};
        respawnlinkedItems[] = {"V_LIB_GER_FieldOfficer","H_LIB_GER_Cap","ItemMap","ItemCompass","ItemWatch"};

        weapons[] = {"CUP_arifle_Steyr_Stg58","LIB_WaltherPPK","LIB_Binocular_GER"};
        respawnWeapons[] = {"CUP_arifle_Steyr_Stg58","LIB_WaltherPPK","LIB_Binocular_GER"};

        magazines[] = {"CUP_20Rnd_762x51_FNFAL_M","fow_8Rnd_9x19","CUP_20Rnd_762x51_FNFAL_M","fow_8Rnd_9x19"};
        respawnMagazines[] = {"CUP_20Rnd_762x51_FNFAL_M","fow_8Rnd_9x19","CUP_20Rnd_762x51_FNFAL_M","fow_8Rnd_9x19"};

        backpack = "B_LIB_GER_SapperBackpack_empty";

        ALiVE_orbatCreator_loadout[] = {{"CUP_arifle_Steyr_Stg58","","","",{"CUP_20Rnd_762x51_FNFAL_M",20},{},"CUP_bipod_FNFAL"},{},{"LIB_WaltherPPK","","","",{"fow_8Rnd_9x19",8},{},""},{"CUP_U_B_BDUv2_dirty_OD",{{"LIB_ACC_K98_Bayo",1},{"PiR_bint",1},{"LIB_M39",1,1},{"CUP_20Rnd_762x51_FNFAL_M",1,20},{"fow_8Rnd_9x19",1,8}}},{"V_LIB_GER_FieldOfficer",{{"PiR_bint",2},{"fow_8Rnd_9x19",5,8},{"LIB_NB39",1,1}}},{"B_LIB_GER_SapperBackpack_empty",{{"CUP_20Rnd_762x51_FNFAL_M",9,20}}},"H_LIB_GER_Cap","",{"LIB_Binocular_GER","","","",{},{},""},{"ItemMap","","","ItemCompass","ItemWatch",""}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

};