//////////////////////////////////////////////////////////////////////////////////
// Config Automatically Generated by ALiVE ORBAT Creator
// Generated with Arma 3 version 206.148470 on Stable branch
// Generated with ALiVE version 1.15.0.2112041
//////////////////////////////////////////////////////////////////////////////////

class CfgFactionClasses {
    class O_RussianNationalReclamationGovernmenthttp_alivemod_com_RussianNationalReclamationGovernmentArmy_West_Russia {
        displayName = "Russian Black League";
        side = 0;
        flag = "\GEISTA3L\geistl_assets_t_flags\data\flag_map\Flag_SOV_URSS_02.paa";
        icon = "\GEISTA3L\geistl_assets_t_flags\data\flag_map\Flag_SOV_URSS_02.paa";
        priority = 0;
    };
};